### ISSUE TITLE
screen flickering

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#9]
after sending a message it looks like the app need a side reload or refreshing screen. this ends up in following case:
1. writing a message and press send
2. write second message immediately after
3. flickering (reload,refresh) interrupts message writing (text row jumps back down to bottom). sometimes flickering happens twice

**Comment by aebruno** [comment]
The screen flickering should be fixed now. The chat text box still closes when a new message arrives if you're in the middle of typing a message. This is slightly annoying but will close for now as the flickering seemed to be the bigger issue.

**Comment by carepack** [comment]
hi aebruno,
i think it isn't solved at all. In the message the flickering has gone. But sending a message and went straight back to message overview, the flickering appears there. But it's much more better now! thx for you're work. and instead of open an issue because of the timestamp thing ... I looked into the message.go and found the string. In the and next time I'll try to make a commit instead of opening an issue ;)

**Comment by aebruno** [comment]
I can reproduce the screen flickering on the main conversation page. It seems to only happen after sending a message and navigating back to the main page. Working on a fix now.

**Comment by carepack** [comment]
morning bruno,
I compiled a new version with this commit https://github.com/aebruno/whisperfish/commit/e3184da027d1cd0aeaf308c507bca9147e5e1e72
Sadly the flickering is still present in overview after sending a message

**Comment by aebruno** [comment]
@carepack think I got the screen flickering sorted out. If you still experience this let me know and I'll re-open.
